In [8]:
#1. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array. 

import numpy as np
l = [23.12,56.20, 100, 36]
print("Original List:",l)
print()
a = np.array(l)
print("One-dimensional NumPy array: ",a)



Original List: [23.12, 56.2, 100, 36]

One-dimensional NumPy array:  [ 23.12  56.2  100.    36.  ]


In [3]:
#2.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. 

import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [12]:
#3. Write a NumPy program to create a null vector of size 10 and update sixth value to 11. 

import numpy as np
x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)




[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [11]:
#4. Write a NumPy program to create an array with values ranging from 12 to 38. 

import numpy as np
x = np.arange(12, 38)
print(x)


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [14]:
#5. Write a NumPy program to reverse an array (first element becomes last). 

import numpy as np
import numpy as np
x = np.arange(2, 20)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)




Original array:
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reverse array:
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2]


In [15]:
#6. Write a NumPy program to convert an array to a float type.  


import numpy as np
import numpy as np
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)




Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


In [16]:
#7. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 



import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)




Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
#8. Write a NumPy program to add a border (filled with 0's) around an existing array.  



import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)


Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
#9. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.  
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
#10. Write a NumPy program to convert a list and tuple into arrays. 


import numpy as np
my_list = [1, 2, 3, 4, 5, 6, 7, 8]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([8, 4, 6], [1, 2, 3])
print("Tuple to array: ")
print(np.asarray(my_tuple))




List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


In [20]:
#11. Write a NumPy program to append values to the end of an array.  


import numpy as np
x = [10, 20, 30]
print("Original array:")
print(x)
x = np.append(x, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:")
print(x)


Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]


In [22]:
#12. Write a NumPy program to create an empty and a full array. 
 

import numpy as np
# Create an empty array
x = np.empty((3,4))
print(x)
# Create a full array
y = np.full((3,3),6)
print(y)



[[1.03306725e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [1.13073288e+277 2.42336543e-057 5.94746209e-091 5.49604112e+170]
 [8.31526244e-072 1.73735576e-047 3.99910963e+252 4.93432906e+257]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [25]:
#13. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array. 
 

import numpy as np
fvalues = [0, 12, 45.21, 34, 99.91]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:") 
print(5*F/9 - 5*32/9)


Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [26]:
#14. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.  


import numpy as np
x = np.sqrt([1+0j])
y = np.sqrt([0+1j])
print("Original array:x ",x)
print("Original array:y ",y)
print("Real part of the array:")
print(x.real)
print(y.real)
print("Imaginary part of the array:")
print(x.imag)
print(y.imag)


Original array:x  [1.+0.j]
Original array:y  [0.70710678+0.70710678j]
Real part of the array:
[1.]
[0.70710678]
Imaginary part of the array:
[0.]
[0.70710678]
