In [8]:
#1.Extract data from the given SalaryGender CSV file and store the data from each column in a separate NumPy array
import numpy as np
import pandas as pd
import os 
import matplotlib.pyplot as plt


os.getcwd()
os.chdir ('C:\\Users\\Pavan Jadhav\\Desktop\\Python')

os.getcwd()


df = pd.read_csv('SalaryGender.csv')
df


salary = np.array(df['Salary'])
salary


gender = np.array(df['Gender'])
gender


age = np.array(df['Age'])
age


phd = np.array(df['PhD'])
phd







array([1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0], dtype=int64)

In [10]:
#2.Find:

#The number of men with a PhD

#The number of women with a PhD

df = pd.read_csv('SalaryGender.csv', delimiter=',')
salary = np.array(df['Salary'])
gender = np.array(df['Gender'])
phd = np.array(df['PhD'])
age = np.array(df['Age'])

men_count = 0
women_count = 0

for i in range(0, 100):
    if gender[i] == 1 and phd[i] == 1:
        men_count +=1
    if gender[i] == 0 and phd[i] == 1:
        women_count +=1

print('Men Count', men_count)
print('Woman Count',women_count)





Men Count 24
Woman Count 15


In [11]:
#3.Use SalaryGender CSV file. Store the “Age” and “PhD” columns in one DataFrame and delete the data of all people who don’t have a PhD

df = pd.read_csv('SalaryGender.csv', delimiter=',')
salary = np.array(df['Salary'])
gender = np.array(df['Gender'])
phd = np.array(df['PhD'])
age = np.array(df['Age'])


frame = pd.DataFrame()
frame["Age"] = age
frame["PhD"] = phd


for i in range(0, 100):
    if frame.loc[i]["PhD"] == 0:
        frame = frame.drop(i)
print('Number of records',len(frame))
print(frame)



Number of records 39
    Age  PhD
0    47    1
1    65    1
4    53    1
8    44    1
9    63    1
12   60    1
17   47    1
18   66    1
19   45    1
25   66    1
26   36    1
28   51    1
29   65    1
30   45    1
31   52    1
32   54    1
38   34    1
41   58    1
42   77    1
45   48    1
47   49    1
49   65    1
54   49    1
56   61    1
57   43    1
60   66    1
63   56    1
73   71    1
76   69    1
77   58    1
79   32    1
80   33    1
81   32    1
87   42    1
89   51    1
90   71    1
92   55    1
94   55    1
96   56    1


In [12]:
#4.Calculate the total number of people who have a PhD degree from SalaryGender CSV file.



df = pd.read_csv('SalaryGender.csv', delimiter=',')
phdcount=0


for i in range(0, 100):
    if df.iloc[i]['PhD'] == 1:
        phdcount=phdcount+1


        
print('PhD Count:',phdcount)





PhD Count: 39


In [17]:
#5.How do you Count The Number Of Times Each Value Appears In An Array Of Integers?

#[0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9]



arr = np.array([0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9])


print(np.bincount(arr))


[4 2 1 1 3 2 0 0 0 1]


In [18]:
#6.Create a numpy array [[0, 1, 2], [ 3, 4, 5], [ 6, 7, 8],[ 9, 10, 11]]) and filter the elements greater than 5.

import numpy as np
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]])
print('Our array is:' )
print(x)
print('\n')


# Now we will print the items greater than 5
print('The items greater than 5 are:' )


print(x[x > 5])




Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The items greater than 5 are:
[ 6  7  8  9 10 11]


In [19]:
#7.Create a numpy array having NaN (Not a Number) and print it.

#array([ nan, 1., 2., nan, 3., 4., 5.])

#Print the same array omitting all elements which are nan

import numpy
a = numpy.array([numpy.nan, 1,2,numpy.nan,3,4,5])
print(a)
print(a[~numpy.isnan(a)])


[nan  1.  2. nan  3.  4.  5.]
[1. 2. 3. 4. 5.]


In [21]:
#8.Create a 10x10 array with random values and find the minimum and maximum values.


import numpy as np
Z = np.random.random((10,10))
print (pd.DataFrame(Z))




Zmin, Zmax = Z.min(), Z.max()
print ('Min and Max Values')
print(Zmin, Zmax)


          0         1         2         3         4         5         6  \
0  0.307382  0.512457  0.533207  0.149744  0.759708  0.260707  0.414497   
1  0.816325  0.624836  0.505880  0.922883  0.451090  0.892336  0.904939   
2  0.945833  0.511767  0.862373  0.081670  0.058552  0.055477  0.185474   
3  0.978448  0.906654  0.701079  0.831064  0.246766  0.398946  0.729343   
4  0.900142  0.051809  0.722204  0.932898  0.344077  0.642874  0.567581   
5  0.610679  0.581772  0.419017  0.407981  0.346451  0.937808  0.342265   
6  0.340462  0.216230  0.165993  0.812920  0.996562  0.512375  0.776855   
7  0.093878  0.881003  0.513449  0.833195  0.516894  0.323230  0.419199   
8  0.865609  0.149096  0.883759  0.595084  0.545043  0.091926  0.621014   
9  0.123709  0.536646  0.559151  0.567099  0.767170  0.022845  0.847590   

          7         8         9  
0  0.262928  0.863482  0.765563  
1  0.712820  0.136735  0.025217  
2  0.788899  0.520389  0.387834  
3  0.088643  0.757965  0.073445  
4  0

In [22]:
#9.Create a random vector of size 30 and find the mean value.


import numpy as np
Z = np.random.random(30)
m = Z.mean()
print(m)


0.5238722171199232


In [23]:
#10.Create numpy array having elements 0 to 10 And negate all the elements between 3 and 9


import numpy as np
Z = np.arange(11)
print ('Array')
print (Z)


Z[(3 < Z) & (Z <= 8)] *= -1
print ('Negeted Array')
print(Z)



Array
[ 0  1  2  3  4  5  6  7  8  9 10]
Negeted Array
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [25]:
#11.Create a random array of 3 rows and 3 columns and sort it according to 1st column, 2nd column or 3rd column.

Z = np.random.randint(0,10,(3,3))
print(Z)
print ()


print(Z[Z[:,1].argsort()])


[[0 3 4]
 [2 4 9]
 [3 2 6]]

[[3 2 6]
 [0 3 4]
 [2 4 9]]


In [28]:
#12.Create a four dimensions array (2,2,2,2) get sum over the last two axis at once.



A = np.random.randint(0,10,(2,2,2,2))
print ('Array')
print (A)


sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print ('Result')
print(sum)






Array
[[[[4 9]
   [4 3]]

  [[7 1]
   [5 4]]]


 [[[8 9]
   [0 7]]

  [[1 9]
   [9 1]]]]
Result
[[20 17]
 [24 20]]


In [30]:
#13.Create a random array ( 5,5) and swap two rows of an array.

A = np.arange(25).reshape(5,5)
print ('Random Array')
print (A)
# First row assigned to Zeroth row and zero row assigned to first row


A[[0,1]] = A[[1,0]]
print ()
print ('Swapped Array')
print(A)


Random Array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Swapped Array
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
